baseURL = 'https://rh-mobb.github.io/mobb_ninja/'
languageCode = 'en-us'
title = 'Managed OpenShift Black Belt - Unofficial Documentation'
theme = "relearn"
DefaultContentLanguage = "en"
pygmentsCodeFences = true
pygmentsStyle = "monokai"
# as the official Hugo documentation recommends, we turn this off for this
# showcase; this allows the published site to be served by both http and https
canonifyURLs = true
# required for official documentation served from subfolder
relativeURLs = false

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# googleanalytics = "UA-123-45"

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

# Keep this as is
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Site params
[params]
alwaysopen = false
collapsibleMenu = true
themeVariant = "red"
# ordersectionsby = "weight" # ordersectionsby = "title"
#color_main = "#CC0000"
# color_second = "#b30000"
# disableSearch = false # default is false
# disableNavChevron = false # set true to hide next/prev chevron, default is false
# menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window

# #editURL = "https://github.com/vjeantet/hugo-theme-docport/edit/master/exampleSite/content/"
# enableGitInfo = true



[mediaTypes]
  [mediaTypes."application/netlifyconfig"]
    suffixes = ["yml"]

[outputFormats]
[outputFormats.netlifyyaml]
mediaType = "application/netlifyconfig"
isPlainText = true
isHTML = false
notAlternative = true

[markup.goldmark.renderer]
unsafe = true

# Code highlight configuration
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2

#
# top menu shotcuts
#
[[menu.shortcuts]]
name = "Github"
identifier = "ds"
url = "https://github.com/vjeantet/hugo-theme-docport"
weight = 10

[[menu.shortcuts]]
name = "Download"
url = "https://github.com/vjeantet/hugo-theme-docport/archive/master.zip"
weight = 11

[[menu.shortcuts]]
name = "Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "Credits"
url = "/docport-theme/credits/"
weight = 30
