apiVersion: v1
kind: Secret
metadata:
  name: store-credentials
  namespace: thanos-receiver
stringData:
  store-secret.yaml: |
    type: S3
    config:
      bucket: "my-thanos-metrics"
      region: "us-east-2"
      access_key: "AKIAZTOQFUEZIFPAOWSX"
      secret_key: ""
      endpoint: "s3.us-east-2.amazonaws.com"
      signature_version2: false
