apiVersion: v1
kind: Secret
metadata:
  name: store-credentials
  namespace: thanos-receiver
stringData:
  store-secret.yaml: |
    type: AZURE
    config:
      storage_account: "thanosreceiver"
      storage_account_key: ""
      container: "thanosmetrics"
      max_retries: 0